package com.technods.rh.entities;

// Generated 11 avr. 2016 23:43:33 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Candidat generated by hbm2java
 */
@Entity
@Table(name = "candidat", catalog = "explorerrh")
public class Candidat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcandidat;
	private String name;
	private String firstName;
	private byte[] cv;
	private byte[] photo;
	private String niveau;
	private String poste;
	private String statut;
	private Interview interviews;

	public Candidat() {
	}

	public Candidat(int idcandidat) {
		this.idcandidat = idcandidat;
	}

	public Candidat(int idcandidat, String name, String firstName, byte[] cv,
			byte[] photo, String niveau, String poste, String statut,
			Set<Interview> interviews) {
		this.idcandidat = idcandidat;
		this.name = name;
		this.firstName = firstName;
		this.cv = cv;
		this.photo = photo;
		this.niveau = niveau;
		this.poste = poste;
		this.statut = statut;
		this.interviews = interviews;
	}

	@Id
	@Column(name = "idcandidat", unique = true, nullable = false)
	public int getIdcandidat() {
		return this.idcandidat;
	}

	public void setIdcandidat(int idcandidat) {
		this.idcandidat = idcandidat;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "firstname", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "cv")
	public byte[] getCv() {
		return this.cv;
	}

	public void setCv(byte[] cv) {
		this.cv = cv;
	}

	@Column(name = "photo")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	@Column(name = "niveau", length = 45)
	public String getNiveau() {
		return this.niveau;
	}

	public void setNiveau(String niveau) {
		this.niveau = niveau;
	}

	@Column(name = "poste", length = 45)
	public String getPoste() {
		return this.poste;
	}

	public void setPoste(String poste) {
		this.poste = poste;
	}

	@Column(name = "statut", length = 45)
	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidat")
	public Set<Interview> getInterviews() {
		return this.interviews;
	}

	public void setInterviews(Set<Interview> interviews) {
		this.interviews = interviews;
	}

}
