package com.technods.rh.entities;

// Generated 11 avr. 2016 23:43:33 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Interview generated by hbm2java
 */
@Entity
@Table(name = "interview", catalog = "explorerrh")
public class Interview implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idinterview;
	private Candidat candidat;
	private Employee employee;
	private Date date;
	private String level;

	public Interview() {
	}

	public Interview(int idinterview) {
		this.idinterview = idinterview;
	}

	public Interview(int idinterview, Candidat candidat, Employee employee,
			Date date, String level) {
		this.idinterview = idinterview;
		this.candidat = candidat;
		this.employee = employee;
		this.date = date;
		this.level = level;
	}

	@Id
	@Column(name = "idinterview", unique = true, nullable = false)
	public int getIdinterview() {
		return this.idinterview;
	}

	public void setIdinterview(int idinterview) {
		this.idinterview = idinterview;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidat")
	public Candidat getCandidat() {
		return this.candidat;
	}

	public void setCandidat(Candidat candidat) {
		this.candidat = candidat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "interviewer")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "level", length = 45)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

}
