package com.technods.rh.entities;

// Generated 11 avr. 2016 23:43:33 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "explorerrh")
public class Message implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idmessage;
	private Employee employeeByReceiver;
	private Employee employeeBySender;
	private String messageDesc;
	private String object;
	private byte[] pj;

	public Message() {
	}

	public Message(Employee employeeByReceiver, Employee employeeBySender,
			String messageDesc, String object, byte[] pj) {
		this.employeeByReceiver = employeeByReceiver;
		this.employeeBySender = employeeBySender;
		this.messageDesc = messageDesc;
		this.object = object;
		this.pj = pj;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idmessage", unique = true, nullable = false)
	public Integer getIdmessage() {
		return this.idmessage;
	}

	public void setIdmessage(Integer idmessage) {
		this.idmessage = idmessage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "receiver")
	public Employee getEmployeeByReceiver() {
		return this.employeeByReceiver;
	}

	public void setEmployeeByReceiver(Employee employeeByReceiver) {
		this.employeeByReceiver = employeeByReceiver;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender")
	public Employee getEmployeeBySender() {
		return this.employeeBySender;
	}

	public void setEmployeeBySender(Employee employeeBySender) {
		this.employeeBySender = employeeBySender;
	}

	@Column(name = "message", length = 555)
	public String getMessageDesc() {
		return this.messageDesc;
	}

	public void setMessageDesc(String message) {
		this.messageDesc = message;
	}

	@Column(name = "pj")
	public byte[] getPj() {
		return this.pj;
	}

	public void setPj(byte[] pj) {
		this.pj = pj;
	}

	@Column(name = "object", length = 105)
	public String getObject() {
		return object;
	}

	public void setObject(String object) {
		this.object = object;
	}
}
