package com.technods.rh.entities;

// Generated 11 avr. 2016 23:43:33 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "explorerrh")
public class Ticket implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idticket;
	private Employee employeeBySender;
	private Employee employeeByReceiver;
	private String type;
	private String title;
	private String description;
	private String statut;

	public Ticket() {
	}

	public Ticket(Employee employeeBySender, Employee employeeByReceiver,
			String type, String title, String description, String statut) {
		this.employeeBySender = employeeBySender;
		this.employeeByReceiver = employeeByReceiver;
		this.type = type;
		this.title = title;
		this.description = description;
		this.statut = statut;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idticket", unique = true, nullable = false)
	public Integer getIdticket() {
		return this.idticket;
	}

	public void setIdticket(Integer idticket) {
		this.idticket = idticket;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender")
	public Employee getEmployeeBySender() {
		return this.employeeBySender;
	}

	public void setEmployeeBySender(Employee employeeBySender) {
		this.employeeBySender = employeeBySender;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "receiver")
	public Employee getEmployeeByReceiver() {
		return this.employeeByReceiver;
	}

	public void setEmployeeByReceiver(Employee employeeByReceiver) {
		this.employeeByReceiver = employeeByReceiver;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "statut", length = 45)
	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

}
